version: '3.3'

services:
  agent:
    image: portainer/agent:latest
    container_name: portainer-agent-service
    restart: unless-stopped
    ports:
      - "9001:9001"
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
      - type: bind
        source: /var/lib/docker/volumes
        target: /var/lib/docker/volumes

  reverse-proxy:
    image: 192.168.254.100:5000/nginx-minaev:latest
    container_name: nginx_proxy_service
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
